from meta import db
from models.hardware import Hardware


class case(Hardware):
    serie = db.StringField(max_length=50)
    barebonetype = db.StringField(max_length=200)
    case_bay_extern = db.StringField(max_length=50)
    socket = db.StringField(max_length=200)
    cpu_soc = db.StringField(max_length=200)
    memory_type_motherboard = db.StringField(max_length=200)
    form_factor = db.StringField(max_length=200)
    power_supply_included = db.StringField(max_length=200)
    power_supply_form_factor = db.StringField(max_length=50)
    power_supply_location = db.StringField(max_length=50)
    materials_steel = db.StringField(max_length=50)
    connections = db.StringField(max_length=200)
    harddrive_bus = db.StringField(max_length=200)
    videochip = db.StringField(max_length=200)
    case_supply = db.StringField(max_length=200)
    ethernet_connection = db.StringField(max_length=200)
    connection_wlan = db.StringField(max_length=200)
    bluetooth_connection = db.StringField(max_length=200)
    usb_connection = db.StringField(max_length=200)
    audio_outputs = db.StringField(max_length=200)
    video_outputs = db.StringField(max_length=200)
    fan_ports = db.StringField(max_length=50)
    cpu_cooler_maximum_height = db.StringField(max_length=50)
    graphics_card_maximum_length = db.StringField(max_length=50)
    case_panel = db.StringField(max_length=50)
    connections_front = db.StringField(max_length=200)
    materials = db.StringField(max_length=200)
    colors = db.StringField(max_length=200)
    case_bay_intern = db.StringField(max_length=200)
    height = db.StringField(max_length=200)
    width = db.StringField(max_length=200)
    depth = db.StringField(max_length=200)
    volume = db.StringField(max_length=50)
    weight = db.StringField(max_length=50)
    bundled_fans = db.StringField(max_length=50)
    case_type = db.StringField(max_length=50)
    warranty = db.StringField(max_length=50)
    cabel_management = db.StringField(max_length=50)
    particulars = db.StringField(max_length=200)
