from meta import db
from models.hardware import Hardware


class case(Hardware):
    Serie = db.StringField(max_length=50)
    Barebonetype = db.StringField(max_length=200)
    Behuizing_bay_extern = db.StringField(max_length=50)
    Socket = db.StringField(max_length=200)
    CPU_SoC = db.StringField(max_length=200)
    Geheugentype_moederbord = db.StringField(max_length=200)
    Form_Factor = db.StringField(max_length=200)
    Inclusief_voeding = db.StringField(max_length=200)
    Voeding_form_factor = db.StringField(max_length=50)
    Voeding_plaats = db.StringField(max_length=50)
    Materialen_Staal = db.StringField(max_length=50)
    Aansluitingen = db.StringField(max_length=200)
    Hardeschijf_bus = db.StringField(max_length=200)
    Videochip = db.StringField(max_length=200)
    Behuizing_Voeding = db.StringField(max_length=200)
    Verbinding_Ethernet = db.StringField(max_length=200)
    Verbinding_wlan = db.StringField(max_length=200)
    Bluetooth_versie = db.StringField(max_length=200)
    Verbinding_USB_FW = db.StringField(max_length=200)
    Audio_uitgangen = db.StringField(max_length=200)
    Video_uit = db.StringField(max_length=200)
    Fan_poorten = db.StringField(max_length=50)
    CPU_koeler_maximum_hoogte = db.StringField(max_length=50)
    Grafische_kaart_maximum_lengte = db.StringField(max_length=50)
    Behuizing_Panel = db.StringField(max_length=50)
    Aansluitingen_voorzijde = db.StringField(max_length=200)
    Materialen = db.StringField(max_length=200)
    Kleuren = db.StringField(max_length=200)
    Behuizing_bay_intern = db.StringField(max_length=200)
    Hoogte = db.StringField(max_length=200)
    Breedte = db.StringField(max_length=200)
    Diepte = db.StringField(max_length=200)
    Volume = db.StringField(max_length=50)
    Gewicht = db.StringField(max_length=50)
    Meegeleverde_fans = db.StringField(max_length=50)
    Behuizingtype = db.StringField(max_length=50)
    Fabrieksgarantie = db.StringField(max_length=50)
    Kabelmanagement = db.StringField(max_length=50)
    Bijzonderheden = db.StringField(max_length=200)
