from mongoengine import StringField
from models.hardware import Hardware


class case(Hardware):
    serie = StringField(max_length=50)
    barebonetype = StringField(max_length=200)
    case_bay_extern = StringField(max_length=50)
    socket = StringField(max_length=200)
    cpu_soc = StringField(max_length=200)
    memory_type_motherboard = StringField(max_length=200)
    form_factor = StringField(max_length=200)
    power_supply_included = StringField(max_length=200)
    power_supply_form_factor = StringField(max_length=50)
    power_supply_location = StringField(max_length=50)
    materials_steel = StringField(max_length=50)
    connections = StringField(max_length=200)
    harddrive_bus = StringField(max_length=200)
    videochip = StringField(max_length=200)
    case_supply = StringField(max_length=200)
    ethernet_connection = StringField(max_length=200)
    connection_wlan = StringField(max_length=200)
    bluetooth_connection = StringField(max_length=200)
    usb_connection = StringField(max_length=200)
    audio_outputs = StringField(max_length=200)
    video_outputs = StringField(max_length=200)
    fan_ports = StringField(max_length=50)
    cpu_cooler_maximum_height = StringField(max_length=50)
    graphics_card_maximum_length = StringField(max_length=50)
    case_panel = StringField(max_length=50)
    connections_front = StringField(max_length=200)
    materials = StringField(max_length=200)
    colors = StringField(max_length=200)
    case_bay_intern = StringField(max_length=200)
    height = StringField(max_length=200)
    width = StringField(max_length=200)
    depth = StringField(max_length=200)
    volume = StringField(max_length=50)
    weight = StringField(max_length=50)
    bundled_fans = StringField(max_length=50)
    case_type = StringField(max_length=50)
    warranty = StringField(max_length=50)
    cabel_management = StringField(max_length=50)
    particulars = StringField(max_length=200)
