from mongoengine import StringField
from models.hardware import Hardware


class GraphicsCard(Hardware):
    videochip = StringField(max_length=200)
    chipset_generation = StringField(max_length=200)
    video_chip_manufacturer = StringField(max_length=200)
    rated_speed_video_chip = StringField(max_length=200)
    max_Turbo_Frequency = StringField(max_length=200)
    computing_cores = StringField(max_length=200)
    memory_size = StringField(max_length=200)
    memory_type = StringField(max_length=200)
    rated_speed_video_memory_chip = StringField(max_length=200)
    memory_bus_width = StringField(max_length=200)
    card_interface = StringField(max_length=200)
    video_out = StringField(max_length=200)
    highest_hdm_version = StringField(max_length=200)
    highest_displayPort_version = StringField(max_length=200)
    video_adapter = StringField(max_length=200)
    directx_version = StringField(max_length=200)
    openl_version = StringField(max_length=200)
    shader_model = StringField(max_length=200)
    length = StringField(max_length=200)
    height = StringField(max_length=200)
    width = StringField(max_length=200)
    number_of_slots = StringField(max_length=200)
    number_of_pins = StringField(max_length=200)
    number_of_6_pins = StringField(max_length=200)
    number_of_8_pins = StringField(max_length=200)
    power_consumption = StringField(max_length=200)
    type_cooling = StringField(max_length=200)
    link_interface = StringField(max_length=200)
