from mongoengine import StringField
from models.hardware import Hardware


class Processor(Hardware):
    serie = StringField(max_length=200)
    product = StringField(max_length=200)
    socket = StringField(max_length=200)
    number_of_cores = StringField(max_length=200)
    cpu_spec_number = StringField(max_length=200)
    speed = StringField(max_length=200)
    maximum_turbo_frequency = StringField(max_length=200)
    memory_specification = StringField(max_length=200)
    bus_speed = StringField(max_length=200)
    process_technology = StringField(max_length=200)
    thermal_design_power = StringField(max_length=200)
    integrated_graphics = StringField(max_length=200)
    gpu = StringField(max_length=200)
    rated_speed_video_chip = StringField(max_length=200)
    maximum_speed_video_chip = StringField(max_length=200)
    cpu_cache_level_1 = StringField(max_length=200)
    cpu_cache_level_2 = StringField(max_length=200)
    cpu_cache_level_3 = StringField(max_length=200)
    threads_old = StringField(max_length=200)
    threads = StringField(max_length=200)
    threads_new = StringField(max_length=200)
    virtualization = StringField(max_length=200)
    virtualization_type = StringField(max_length=200)
    cpu_multiplier = StringField(max_length=200)
    cpu_stepping = StringField(max_length=200)
    cpu_instructieset = StringField(max_length=200)
    type_cooling = StringField(max_length=200)
    sale_status_cpu = StringField(max_length=200)
    warranty = StringField(max_length=200)
    particulars = StringField(max_length=200)
