from meta import db
from models.hardware import Hardware


class Processor(Hardware):
    serie = db.StringField(max_length=200)
    product = db.StringField(max_length=200)
    socket = db.StringField(max_length=200)
    number_of_cores = db.StringField(max_length=200)
    cpu_spec_number = db.StringField(max_length=200)
    speed = db.StringField(max_length=200)
    maximum_turbo_frequency = db.StringField(max_length=200)
    memory_specification = db.StringField(max_length=200)
    bus_speed = db.StringField(max_length=200)
    process_technology = db.StringField(max_length=200)
    thermal_design_power = db.StringField(max_length=200)
    integrated_graphics = db.StringField(max_length=200)
    gpu = db.StringField(max_length=200)
    rated_speed_video_chip = db.StringField(max_length=200)
    maximum_speed_video_chip = db.StringField(max_length=200)
    cpu_cache_level_1 = db.StringField(max_length=200)
    cpu_cache_level_2 = db.StringField(max_length=200)
    cpu_cache_level_3 = db.StringField(max_length=200)
    threads_old = db.StringField(max_length=200)
    threads = db.StringField(max_length=200)
    threads_new = db.StringField(max_length=200)
    virtualization = db.StringField(max_length=200)
    virtualization_type = db.StringField(max_length=200)
    cpu_multiplier = db.StringField(max_length=200)
    cpu_stepping = db.StringField(max_length=200)
    cpu_instructieset = db.StringField(max_length=200)
    type_cooling = db.StringField(max_length=200)
    sale_status_cpu = db.StringField(max_length=200)
    warranty = db.StringField(max_length=200)
    particulars = db.StringField(max_length=200)
