from meta import db
from models.hardware import Hardware


class Processor(Hardware):
    Serie = db.StringField(max_length=200)
    Product = db.StringField(max_length=200)
    Socket = db.StringField(max_length=200)
    Aantal_cores = db.StringField(max_length=200)
    CPU_sSpec_Number = db.StringField(max_length=200)
    Snelheid = db.StringField(max_length=200)
    Maximale_turbo_frequentie = db.StringField(max_length=200)
    Geheugen_Specificatie = db.StringField(max_length=200)
    Bus_snelheid = db.StringField(max_length=200)
    Procestechnologie = db.StringField(max_length=200)
    Thermal_Design_Power = db.StringField(max_length=200)
    Geintegreerde_graphics = db.StringField(max_length=200)
    Gpu = db.StringField(max_length=200)
    Nominale_snelheid_videochip = db.StringField(max_length=200)
    Maximale_snelheid_videochip = db.StringField(max_length=200)
    CPU_Cache_Level_1 = db.StringField(max_length=200)
    CPU_Cache_Level_2 = db.StringField(max_length=200)
    CPU_Cache_Level_3 = db.StringField(max_length=200)
    Threads_oud = db.StringField(max_length=200)
    Threads = db.StringField(max_length=200)
    Threads_nieuw = db.StringField(max_length=200)
    Virtualisatie = db.StringField(max_length=200)
    Virtualisatie_type = db.StringField(max_length=200)
    CPU_Multiplier = db.StringField(max_length=200)
    CPU_stepping = db.StringField(max_length=200)
    CPU_Instructieset = db.StringField(max_length=200)
    Type_koeling = db.StringField(max_length=200)
    Verkoopstatus_CPU = db.StringField(max_length=200)
    Fabrieksgarantie = db.StringField(max_length=200)
    Bijzonderheden = db.StringField(max_length=200)
