    import json
import logging

from marshmallow import Schema, fields
from marshmallow.fields import Email, String, Integer, List, Boolean, Float

log = logging.getLogger(__name__)


class HardwareSchema(Schema):
    # category = ReferenceField('Category')
    name = String(required=False)
    subname = String(required=False)
    info = String(required=False)
    stock = String(required=False)
    image = String(required=False)
    ean = String(required=False)
    sku = String(required=False)
    SKU = String(required=False)
    link = String(required=False)
    brand = String(required=False)
    execution = String(required=False)


class CaseSchema(Schema):
    serie = String(required=False)
    barebonetype = String(required=False)
    case_bay_extern = String(required=False)
    socket = String(required=False)
    cpu_soc = String(required=False)
    memory_type_motherboard = String(required=False)
    form_factor = String(required=False)
    power_supply_included = String(required=False)
    power_supply_form_factor = String(required=False)
    power_supply_location = String(required=False)
    materials_steel = String(required=False)
    connections = String(required=False)
    harddrive_bus = String(required=False)
    videochip = String(required=False)
    case_supply = String(required=False)
    ethernet_connection = String(required=False)
    connection_wlan = String(required=False)
    bluetooth_connection = String(required=False)
    usb_connection = String(required=False)
    audio_outputs = String(required=False)
    video_outputs = String(required=False)
    fan_ports = String(required=False)
    cpu_cooler_maximum_height = String(required=False)
    graphics_card_maximum_length = String(required=False)
    case_panel = String(required=False)
    connections_front = String(required=False)
    materials = String(required=False)
    colors = String(required=False)
    case_bay_intern = String(required=False)
    height = String(required=False)
    width = String(required=False)
    depth = String(required=False)
    volume = String(required=False)
    weight = String(required=False)
    bundled_fans = String(required=False)
    case_type = String(required=False)
    warranty = String(required=False)
    cabel_management = String(required=False)
    particulars = String(required=False)


class CoolerSchema(Schema):
    Socket = String(required=False)
    connection_processor_cooling = String(required=False)
    heatpipes = String(required=False)
    volume = String(required=False)
    rotational_speed_min = String(required=False)
    rotational_speed_max = String(required=False)
    type_cooling = String(required=False)
    height = String(required=False)
    diameter = String(required=False)
    colors = String(required=False)
    materials = String(required=False)
    warranty = String(required=False)
    particulars = String(required=False)


class DvdSchema(Schema):
    drive_bay = String(required=False)
    Optical_drive_type = String(required=False)
    hard_drive_bus = String(required=False)
    dvd_read_speed = String(required=False)
    dvd_Writing_speed_sl = String(required=False)
    dvd_Writing_speed_dl = String(required=False)
    dvd_Rewrite_speed = String(required=False)
    cd_read_speed = String(required=False)
    cd_writing_speed = String(required=False)
    colors = String(required=False)


class GraphicsCardSchema(Schema):
    videochip = String(required=False)
    chipset_generation = String(required=False)
    video_chip_manufacturer = String(required=False)
    rated_speed_video_chip = String(required=False)
    max_Turbo_Frequency = String(required=False)
    computing_cores = String(required=False)
    memory_size = String(required=False)
    memory_type = String(required=False)
    rated_speed_video_memory_chip = String(required=False)
    memory_bus_width = String(required=False)
    card_interface = String(required=False)
    video_out = String(required=False)
    highest_hdm_version = String(required=False)
    highest_displayPort_version = String(required=False)
    video_adapter = String(required=False)
    directx_version = String(required=False)
    openl_version = String(required=False)
    shader_model = String(required=False)
    length = String(required=False)
    height = String(required=False)
    width = String(required=False)
    number_of_slots = String(required=False)
    number_of_pins = String(required=False)
    number_of_6_pins = String(required=False)
    number_of_8_pins = String(required=False)
    power_consumption = String(required=False)
    type_cooling = String(required=False)
    link_interface = String(required=False)


class HardDriveSchema(Schema):
    serie = String(required=False)
    product = String(required=False)
    storage = String(required=False)
    hard_drive_bus = String(required=False)
    case_bay_intern = String(required=False)
    height = String(required=False)
    rotation_speed = String(required=False)
    drive_cache = String(required=False)
    command_queuing = String(required=False)
    power_reading = String(required=False)
    power_writing = String(required=False)
    prive_per_gb = String(required=False)
    warranty = String(required=False)
    ssd_type = String(required=False)
    ssd_controller = String(required=False)
    ssd_properties = String(required=False)
    hard_drive_bus_intern = String(required=False)
    hdd_ssd_connection = String(required=False)
    sequential_read = String(required=False)
    sequential_write = String(required=False)
    read_random_4k = String(required=False)
    write_random_4k = String(required=False)


class MemorySchema(Schema):
    memory_specification = StringField(max_length=500)
    serie = String(required=False)
    product = String(required=False)
    memory_size = String(required=False)
    number = String(required=False)
    module_size = String(required=False)
    Price_per_gb = String(required=False)
    memory_type = String(required=False)
    memory_specification = String(required=False)
    low_voltage_ddr = String(required=False)
    memory_cas_latency = String(required=False)
    tension = String(required=False)
    warranty = String(required=False)
    particulars = String(required=False)


class MotherBoardSchema(Schema):
    serie = String(required=False)
    product = String(required=False)
    socket = String(required=False)
    number_of_sockets = String(required=False)
    form_factor = String(required=False)
    bios_or_uefi = String(required=False)
    dual_or_single_bios_uefi = String(required=False)
    motherboard_chipset = String(required=False)
    memory_type = String(required=False)
    maximum_memory_size = String(required=False)
    hard_drive_bus = String(required=False)
    raid_modi = String(required=False)
    card_interface = String(required=False)
    number_of_pcie = String(required=False)
    link_interface = String(required=False)
    ethernet_connection = String(required=False)
    network_chip = String(required=False)
    bluetooth_available = String(required=False)
    usb_connection = String(required=False)
    video_out = String(required=False)
    connection = String(required=False)
    audio_channels = String(required=False)
    audio_outputs = String(required=False)
    audio_chips = String(required=False)


class PowerSupplySchema(Schema):
    power_watt = String(required=False)
    product = String(required=False)
    _12v_rails = String(required=False)
    capacity_12v1_rail = String(required=False)
    power_certification = String(required=False)
    number_of_sata_connectors = String(required=False)
    number_molex_connectors = String(required=False)
    pci_express_connectors = String(required=False)
    number_6_pins_connections = String(required=False)
    number_6_2_pins_connections = String(required=False)
    modular = String(required=False)
    number_of_fans = String(required=False)
    diameter_fan = String(required=False)
    cooling_type = String(required=False)
    fan_location = String(required=False)
    Power_type = String(required=False)
    power_surge_protection = String(required=False)
    width = String(required=False)
    height = String(required=False)
    depth = String(required=False)
    warranty = String(required=False)
    particulars = String(required=False)
    

class ProcessorSchema(Schema):
    serie = String(required=False)
    product = String(required=False)
    socket = String(required=False)
    number_of_cores = String(required=False)
    cpu_spec_number = String(required=False)
    speed = String(required=False)
    maximum_turbo_frequency = String(required=False)
    memory_specification = String(required=False)
    bus_speed = String(required=False)
    process_technology = String(required=False)
    thermal_design_power = String(required=False)
    integrated_graphics = String(required=False)
    gpu = String(required=False)
    rated_speed_video_chip = String(required=False)
    maximum_speed_video_chip = String(required=False)
    cpu_cache_level_1 = String(required=False)
    cpu_cache_level_2 = String(required=False)
    cpu_cache_level_3 = String(required=False)
    threads_old = String(required=False)
    threads = String(required=False)
    threads_new = String(required=False)
    virtualization = String(required=False)
    virtualization_type = String(required=False)
    cpu_multiplier = String(required=False)
    cpu_stepping = String(required=False)
    cpu_instructieset = String(required=False)
    type_cooling = String(required=False)
    sale_status_cpu = String(required=False)
    warranty = String(required=False)
    particulars = String(required=False)
